### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by KabinaThapa** [KabinaThapa/ecommerce#1]
- Initialize a new Next.js project, set up project structure, and install necessary dependencies.

Estimated time to complete: 1day

**Comment by KabinaThapa** [comment]
![Image](https://github.com/KabinaThapa/ecommerce/assets/108284958/a073bf33-84b7-4405-a43c-3ac1bb89dae1)

**Comment by yogeshtakeo** [comment]
Project Setup looks good now for the good parts ❤️ Coding
