### ISSUE TITLE
Global state management setup for products data

### ISSUE THREAD

**Issue by KabinaThapa** [KabinaThapa/ecommerce#12]
- Configure Redux with Redux Toolkit. Set up the store, reducers, and actions to manage global states of product data.

Estimated time to complete: 1 day

**Comment by KabinaThapa** [comment]
![Image](https://github.com/KabinaThapa/ecommerce/assets/108284958/2c534626-e4b2-4064-8fe3-7879139be11c)

**Comment by yogeshtakeo** [comment]
Inititation is good 👌
