### ISSUE TITLE
Create Navbar and Footer component

### ISSUE THREAD

**Issue by KabinaThapa** [KabinaThapa/ecommerce#14]
- Create a reusable navbar and footer component.
- Design and implement a consistent and visually appealing footer and navbar for a website.

**Comment by KabinaThapa** [comment]
![Image](https://github.com/KabinaThapa/ecommerce/assets/108284958/a7176713-c475-4191-ab6c-a7059232a944)



![Image](https://github.com/KabinaThapa/ecommerce/assets/108284958/cac58feb-0b6f-48fb-9c69-32aee1798e20)

**Comment by yogeshtakeo** [comment]
Color Picking mechanism is great ❤️ try to the point designs ☺️
