### ISSUE TITLE
Global State Management Setup

### ISSUE THREAD

**Issue by KabinaThapa** [KabinaThapa/ecommerce#3]
- Configure Redux with Redux Toolkit. Set up the store, reducers, and actions to manage global states like user authentication, cart items, and product data.

Estimated time to complete: 2 days

**Comment by KabinaThapa** [comment]
![Image](https://github.com/KabinaThapa/ecommerce/assets/108284958/c671a4a0-6a72-4dd5-8f0d-a2b56db8b689)

**Comment by yogeshtakeo** [comment]
I see the use of redux in the state management good choice 👍
