### ISSUE TITLE
Authentication Integration

### ISSUE THREAD

**Issue by KabinaThapa** [KabinaThapa/ecommerce#4]
- Create a user authentication system utilizing Json-Auth, Json Server, and Postman. The system should allow users to register, log in, and log out, while managing user data and tokens securely.

Estimated time to complete: 2 day

**Comment by KabinaThapa** [comment]
![Image](https://github.com/KabinaThapa/ecommerce/assets/108284958/f7e0acbb-884e-4109-b1c5-f59810ef3099)



![Image](https://github.com/KabinaThapa/ecommerce/assets/108284958/20a390f1-4037-454b-9111-7b87d4198d48)

**Comment by yogeshtakeo** [comment]
Nice 👍
