### ISSUE TITLE
Product Data Fetching

### ISSUE THREAD

**Issue by KabinaThapa** [KabinaThapa/ecommerce#5]
- Set up data fetching for product information. Use Redux Toolkit's createAsyncThunk to handle API requests and populate the store with fetched data.

Estimated time to complete: 3 days

**Comment by KabinaThapa** [comment]
![Image](https://github.com/KabinaThapa/ecommerce/assets/108284958/7f8ecaba-234f-4759-998a-0c1a683feefd)

**Comment by yogeshtakeo** [comment]
I hope the products are nice
